version: '3.5'

services:

  postgres-master:
    image: saabeilin/postgres-replication:${IMAGE_TAG:-dev}
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - postgres-master:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=masterpass
#      - REPLICATION_PASSWORD=replicationPass


  postgres-standby:
    image: saabeilin/postgres-replication:${IMAGE_TAG:-dev}
    volumes:
      - postgres-standby:/var/lib/postgresql/data
    ports:
      - 5433:5432
    depends_on:
      - postgres-master
    environment:
      - REPLICATION_ROLE=standby
      - POSTGRES_MASTER_SERVICE_HOST=postgres-master
#      - REPLICATION_PASSWORD=replicationPass

volumes:
  postgres-master:
  postgres-standby:
